### ISSUE TITLE
properties table created in user schema instead of 'public'

### ISSUE THREAD

**Issue by mboeringa** [osm2pgsql-dev/osm2pgsql-website#51]
Running the latest master, I noticed the **osm2pgsql_properties** table was not created in schema 'public', but instead the user schema, even though I did **not** set the new **--middle-schema** option on the command line.

This has undoubtedly to do with running PG15, where 'public' is non-writable by default (and is in my database), and falling back to storage in the user schema is essentially fine.

However, the current documentation does not mention special behavior in case the 'public' schema is non-writable, it just reads:

> Version >= 1.9.0 Osm2pgsql stores some properties into a database table. This table is always called osm2pgsql_properties. It will be created in the schema set with the --middle-schema option, or the public schema by default.

See:
https://osm2pgsql.org/doc/manual.html#the-properties-table

Maybe it would be good to amend the manual text for the behavior when 'public' is non-writable, like in PG15 by default.

**Comment by joto** [comment]
The software and docs have been fixed a while ago.
